CREATE TABLE Henkilo (
	id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	etunimi VARCHAR(255) NOT NULL,
	sukunimi VARCHAR(255) NOT NULL,
	sahkoposti VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Tapahtuma (
	id SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nimi VARCHAR(255) NOT NULL,
	pvm VARCHAR(255) NOT NULL,
	aika VARCHAR(255) NOT NULL,
	paikka VARCHAR(255) NOT NULL,
	teema VARCHAR(255) NOT NULL,
	osallistujat INT NOT NULL,
	isanta VARCHAR(255) NOT NULL,
	kuvaus VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE randomOsallistuja (
etunimi VARCHAR(255) NOT NULL,
sukunimi VARCHAR(255) NOT NULL,
sahkoposti VARCHAR(255) NOT NULL,
tapahtumaId SMALLINT NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

